language: node_js

services:
  - docker

node_js:
  - 10

install:
  - npm install typescript
  - npm install -g surge

script:
  - npm run lint
  - npm run build

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t yashkumarverma/shatabdi-express-rewrites .
  - docker push yashkumarverma/shatabdi-express-rewrites
  - surge --project ./coverage/lcov-report --domain shatabdi-express-rewrite-cov.surge.sh
